beer/Beers.Web/Controllers/BeersController.cs
using Beers.Models;
using Beers.Services.Contracts;
using Beers.Services.DTOs;
using Beers.Web.Models;
using Beers.Web.Models.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Beers.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService beerService;
        private readonly UserManager<User> _userManager;

        public BeersController(IBeerService beerService, UserManager<User> userManager)
        {
            this.beerService = beerService;
            _userManager = userManager;
        }


        [Authorize]
        [HttpPost]
        public async Task AddReview(int beerId, int rating, string text)
        {
            var user = await _userManager.GetUserAsync(User);
            await this.beerService.AddReview(user, beerId, rating, text);
        }

        [Authorize]
        [HttpPost]
        public async Task AddToDrunkList(int beerId)
        {
            var user = await _userManager.GetUserAsync(User);
            await this.beerService.AddBeerToAlreadyDrunkList(user, beerId);
        }

        [Authorize]
        [HttpPost]
        public async Task RemoveFromDrunkList(int beerId)
        {
            var user = await _userManager.GetUserAsync(User);
            await this.beerService.RemoveBeerFromAlreadyDrunkList(user, beerId);
        }

        [Authorize]
        [HttpPost]
        public async Task AddToWishList(int beerId)
        {
            var user = await _userManager.GetUserAsync(User);
            await this.beerService.AddToWishList(user, beerId);
        }

        [Authorize]
        [HttpPost]
        public async Task RemoveFromWishList(int beerId)
        {
            var user = await _userManager.GetUserAsync(User);
            await this.beerService.RemoveBeerFromWishList(user, beerId);
        }

        [HttpPost]
        public async Task<IActionResult> Search(string searchText, string country, string style)
        {
            var beers = await this.beerService.GetAllBeers(filter: searchText, country: country, style: style);
            var model = beers.Select(x => x.ToBeerVM());

            return View("Index", model);
        }

        // GET: Beers
        public async Task<IActionResult> Index([FromQuery] int? pagesize, [FromQuery] int? page, [FromQuery] string search, string order, string arrange, string country, string style)
        {
            var beers = await this.beerService.GetAllBeers(page, pagesize, search, order, arrange, country, style);
            var model = beers.Select(x => x.ToBeerVM());

            return View(model);
        }

        //TODO: add Detail View Model
        // GET: Beers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            BeerViewModel beerVM;
            try
            {
                var beer = await this.beerService.GetBeer(id);
                beerVM = beer.ToBeerVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(beerVM);
        }

        [Authorize]
        // GET: Beers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBeerViewModel model)
        {
            //using (var client = new HttpClient())
            //{
            //    client.BaseAddress = new Uri("http://localhost:5000/Beers/Create");

            //    //HTTP POST
            //    //await client.PostAsync(client.BaseAddress, model);
            //    client.PostAsync("http://localhost:5000/Beers/Create", )
            //    var postTask = client.PostAsJsonAsync<CreateBeerViewModel>("beer", model);
            //    postTask.Wait();

            //    var result = postTask.Result;
            //    if (result.IsSuccessStatusCode)
            //    {
            //        return RedirectToAction("Index");
            //    }
            //}

            if (model == null)
                return BadRequest();

            var exists = await this.beerService.BeerExists(model.Name);
            if (exists)
                return StatusCode(409, $"Beer '{model.Name}' already exists.");

            BeerDTO beerDTO = model.ToBeerDTO();

            await this.beerService.Create(beerDTO);
            return RedirectToAction("Index");
        }

        // GET: Beers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            EditBeerViewModel beerVM;
            try
            {
                var beer = await this.beerService.GetBeer(id);
                beerVM = beer.ToEditBeerVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(beerVM);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditBeerViewModel model)
        {
            //if (ModelState.IsValid)
            //{
            try
            {
                var beer = model.ToBeerDTO();
                await this.beerService.Update(id, beer);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
            //}
            //ViewData["BreweryId"] = new SelectList(_context.Breweries, "Id", "Name", beer.BreweryId);
            //ViewData["StyleId"] = new SelectList(_context.Styles, "Id", "Name", beer.StyleId);
            //return View(model);
        }

        // GET: Beers/Delete/5
        //[HttpGet]
        //[Route("Beers/Delete/{id}")]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    BeerViewModel beerVM;
        //    try
        //    {
        //        var beer = await this.beerService.GetBeer(id);
        //        beerVM = beer.ToBeerVM();
        //    }
        //    catch (Exception)
        //    {
        //        return NotFound();
        //        throw;
        //    }

        //    return View(beerVM);
        //}

        // POST: Beers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]//, ActionName("Delete")]
        [Route("Beers/Delete/{id}")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            //var beer = await _context.Beers.FindAsync(id);
            //_context.Beers.Remove(beer);
            //await _context.SaveChangesAsync();
            try
            {
                await this.beerService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //private bool BeerExists(int id)
        //{
        //    return _context.Beers.Any(e => e.Id == id);
        //}
    }
}

beer/Beers.Web/Controllers/StylesController.cs
using Beers.Models;
using Beers.Services.Contracts;
using Beers.Services.DTOs;
using Beers.Web.Models;
using Beers.Web.Models.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Beers.Web.Controllers
{
    public class StylesController : Controller
    {
        private readonly ILogger<StylesController> _logger;
        private readonly IStyleService _styleService;
        private readonly UserManager<User> userManager;

        public StylesController(ILogger<StylesController> logger, IStyleService styleService, UserManager<User> userManager)
        {
            _logger = logger;
            _styleService = styleService;
            this.userManager = userManager;
        }


        [HttpPost]
        public async Task<IActionResult> Search(string searchText)
        {
            var beers = await _styleService.GetAllStyles(filter: searchText);
            var model = beers.Select(x => x.ToStyleVM());

            return View("Index", model);
        }

        // GET: Styles
        public async Task<IActionResult> Index([FromQuery] int? pagesize, [FromQuery] int? page, [FromQuery] string search, string order, string arrange)
        {
            var user = await this.userManager.GetUserAsync(User);
            var styles = await _styleService.GetAllStyles(page, pagesize, search, order, arrange);
            var model = styles.Select(x => x.ToStyleVM());

            return View(model);
        }

        //TODO: add Detail View Model
        // GET: Styles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            StyleViewModel styleVM;
            try
            {
                var style = await _styleService.GetStyle(id);
                styleVM = style.ToStyleVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(styleVM);
        }

        [Authorize(Roles = "Admin")]
        // GET: Styles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Styles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateStyleViewModel model)
        {
            if (model == null)
                return BadRequest();

            var exists = await _styleService.StyleExists(model.Name);
            if (exists)
                return StatusCode(409, $"Style '{model.Name}' already exists.");

            StyleDTO styleDTO = model.ToStyleDTO();

            await _styleService.Create(styleDTO);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        // GET: Styles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            EditStyleViewModel editStyleVM;
            try
            {
                var style = await _styleService.GetStyle(id);
                editStyleVM = style.ToEditStyleVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(editStyleVM);
        }

        // POST: Styles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditStyleViewModel model)
        {
            try
            {
                var brewery = model.ToStyleDTO();
                await _styleService.Update(id, brewery);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }

        //// GET: Styles/Delete/5
        //[Authorize(Roles = "Admin")]
        //[Route("Styles/Delete/{id}")]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    StyleViewModel styleVM;
        //    try
        //    {
        //        var style = await _styleService.GetStyle(id);
        //        styleVM = style.ToStyleVM();
        //    }
        //    catch (Exception)
        //    {
        //        return NotFound();
        //        throw;
        //    }

        //    return View(styleVM);
        //}

        // POST: Styles/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [Route("Styles/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _styleService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

beer/Beers.Web/Controllers/UsersController.cs
using Beers.Models;
using Beers.Services.Contracts;
using Beers.Services.DTOs;
using Beers.Web.Models;
using Beers.Web.Models.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Beers.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly ILogger<UsersController> _logger;
        private readonly IUserService _userService;
        private readonly UserManager<User> userManager;

        public UsersController(ILogger<UsersController> logger, IUserService userService, UserManager<User> userManager)
        {
            _logger = logger;
            _userService = userService;
            this.userManager = userManager;
        }

        // GET: Users
        public async Task<IActionResult> Index([FromQuery] int? pagesize, [FromQuery] int? page, [FromQuery] string search)
        {
            var users = await _userService.GetAllUsers(page, pagesize, search);
            var model = users.Select(x => x.ToUserVM()).ToList();

            return View(model);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            UserViewModel user;
            try
            {
                var style = await _userService.GetUser(id);
                user = style.ToUserVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RegisterPageViewModel model)
        {
            if (model == null)
                return BadRequest();

            var exists = await _userService.UserExists(model.Name);
            if (exists)
                return StatusCode(409, $"User '{model.Name}' already exists.");

            UserDTO userDTO = model.ToUserDTO();

            await _userService.Create(userDTO);
            return RedirectToAction("Index");
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            EditUserViewModel editStyleVM;
            try
            {
                var style = await _userService.GetUser(id);
                editStyleVM = style.ToEditUserVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(editStyleVM);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditUserViewModel model)
        {
            try
            {
                var user = model.ToUserDTO();
                await _userService.Update(id, user);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }


        //// GET: Users/Delete/5
        //[Route("Users/Delete/{id}")]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    UserViewModel userVM;
        //    try
        //    {
        //        var user = await _userService.GetUser(id);
        //        userVM = user.ToUserVM();
        //    }
        //    catch (Exception)
        //    {
        //        return NotFound();
        //        throw;
        //    }

        //    return View(userVM);
        //}

        // POST: Users/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [Route("Users/Delete/{id}")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                //var user = await this.userManager.FindByIdAsync(id.ToString());
                //user.IsDeleted = true;
                //await this.userManager.DeleteAsync(user);
                await _userService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

       
    }
}

beer/Beers.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Beers.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    @RenderBody()
</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)

beer/Beers.Web/Views/Shared/_MainLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using Beers.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Beers.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/details.css" />

    <link rel="stylesheet" href="~/alertify/alertify.min.css" />
    <link rel="stylesheet" href="~/alertify/themes/bootstrap.css" />

</head>
<body>
    <header>
        <!--<div id="navbar" class="d-flex w-100 b-b-light">
        <div class="d-flex w-100">
            <div class="container">
                <div class="row h-100">
                    <nav class="navbar navbar-expand-lg navbar-light w-100">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                            <img src="~/images/beeroverflow3.svg" alt="BeerOverflow" />
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item active">
                                    <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" href="#">Link</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Dropdown
                                    </a>
                                    <div class="dropdown-menu bg-black" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item text-white" href="#">Action</a>
                                        <a class="dropdown-item text-white" href="#">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item text-white" href="#">Something else here</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                                </li>
                            </ul>-->
        <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
        <!--</div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>-->
        <div id="navbar" class="d-flex w-100 b-b-light">
            <div class="d-flex w-100">
                <div class="container">
                    <div class="row h-100">
                        <nav class="navbar navbar-expand-lg navbar-light w-100">
                            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                                <img src="~/images/beeroverflow3.svg" alt="BeerOverflow" />
                            </a>
                            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="padding: 0;outline: none;">
                                <div class="text-white d-flex flex-column" style="width: 30px;height: 30px;justify-content: space-evenly;">
                                    <div style="width: 100%;height: 2px;background: white;"></div>
                                    <div style="width: 100%;height: 2px;background: white;"></div>
                                    <div style="width: 100%;height: 2px;background: white;"></div>
                                </div>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-controller="Beers" asp-action="Index">Beers</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-controller="Breweries" asp-action="Index">Breweries</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-controller="Styles" asp-action="Index">Styles</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-controller="Countries" asp-action="Index">Countries</a>
                                    </li>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-controller="Account" asp-action="Wishlist">Wishlist</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-controller="Account" asp-action="AlreadyDrunkList">AlreadyDrunkList</a>
                                        </li>
                                    }
                                    @*<li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Dropdown
                                            </a>
                                            <div class="dropdown-menu bg-black" aria-labelledby="navbarDropdown">
                                                <a class="dropdown-item text-white" href="#">Action</a>
                                                <a class="dropdown-item text-white" href="#">Another action</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item text-white" href="#">Something else here</a>
                                            </div>
                                        </li>*@
                                    <li class="nav-item d-flex">
                                        @if (SignInManager.IsSignedIn(User))
                                        {
                                            @if (User.IsInRole("Admin"))
                                            {
                                                <a id="manage" class="font-weight-bold nav-link btn btn-warning mr-2 px-3 text-white d-flex justify-content-center align-items-center" asp-controller="Users" asp-action="Index" title="Manage" style="height: 35px;">Users</a>
                                            }
                                            else
                                            {
                                                <a id="manage" class="nav-link text-white" asp-area="Identity" title="Manage">Hello @UserManager.GetUserName(User)!</a>
                                            }
                                            <form id="logoutForm" class="form-inline" asp-area="Identity" asp-controller="Account" asp-action="Logout">
                                                <button id="logout" type="submit" class="px-3 d-flex justify-content-center align-items-center font-weight-bold register-btn">Logout</button>
                                            </form>
                                        }
                                        else
                                        {
                                            <a class="px-3 d-flex justify-content-center align-items-center font-weight-bold login-btn" id="login" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                            <a class="px-3 d-flex justify-content-center align-items-center font-weight-bold register-btn" id="register" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                        }
                                        @*<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>*@
                                    </li>
                                </ul>
                                <!-- <form class="form-inline my-2 my-lg-0">
                                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                                </form> -->
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main>
        @RenderBody()
    </main>
    <footer class="bg-black text-muted py-3">
        <div class="container">
            &copy; 2020 - Beers.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/alertify.min.js"></script>
    @RenderSection("Scripts", required: false)


</body>

beer/Beers.Web/Views/Shared/_StylePartial.cshtml
@model StyleViewModel

    <div class="card" style="border: none;">
        @if (User.IsInRole("Admin"))
        {
            <div class="controls position-absolute mr-2 mt-2" style="top: 0; right: 0">
                <a class="btn btn-primary" asp-controller="Styles" asp-action="Edit" asp-route-id="@Model.Id" title="EDIT"><i class="far fa-edit"></i></a>
                <button class="btn btn-danger beer-delete" onclick="FastDeleteStyle(@Model.Id)" title="DELETE"><i class="fas fa-trash-alt"></i></button>
            </div>
        }
        <div class="card-body px-0 pt-0">
            <div class="frame">
                <img class="card-img-top" src="~/images/beer-681807_1920.jpg" alt="Card image cap" width="100%">
            </div>
            <div class="p-3">
                <h5 class="card-title">
                    <p class="card-text mb-0 gr-h-family text-primary">
                    </p>
                    <a class="text-black" asp-controller="Styles" asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a>
                </h5>
                <div class="mb-3">
                    <div class="gr-h-family text-muted">Beers @Model.Beers.Count</div>
                </div>
                <div class="d-flex align-items-center justify-content-between">
                    <a class="mbtn-primary px-3 mr-5" asp-controller="Styles" asp-action="Details" asp-route-id="@Model.Id">View more</a>
                    <!-- <div class="d-flex align-items-center" style="min-height: 30px;">
                    <a href="#">Show on map</a>
                </div> -->
                </div>
            </div>
        </div>
    </div>