beer/Beers.Web/Models/BreweryViewModel.cs
using System.Collections.Generic;

namespace Beers.Web.Models
{
    public class BreweryViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        //public string Country { get; set; }
        public CountryViewModel Country { get; set; }
        public ICollection<BeerViewModel> Beers { get; set; } = new List<BeerViewModel>();
    }
}

beer/Beers.Web/Controllers/BreweriesController.cs
using Beers.Services.Contracts;
using Beers.Services.DTOs;
using Beers.Web.Models;
using Beers.Web.Models.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Beers.Web.Controllers
{
    public class BreweriesController : Controller
    {
        private readonly ILogger<BreweriesController> _logger;
        private readonly IBreweryService _breweryService;

        public BreweriesController(ILogger<BreweriesController> logger, IBreweryService breweryService)
        {
            _logger = logger;
            _breweryService = breweryService;
        }

        [HttpPost]
        public async Task<IActionResult> Search(string searchText, string country)
        {
            var beers = await _breweryService.GetAllBreweries(filter: searchText, country: country);
            var model = beers.Select(x => x.ToBreweryVM());

            return View("Index", model);
        }

        // GET: BreweriesController.cs
        public async Task<IActionResult> Index([FromQuery] int? pagesize, [FromQuery] int? page, [FromQuery] string search, string order, string arrange)
        {
            var breweries = await _breweryService.GetAllBreweries(page, pagesize, search, order, arrange);
            var model = breweries.Select(x => x.ToBreweryVM());

            return View(model);
        }

        //TODO: add Detail View Model
        // GET: Breweries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            BreweryViewModel breweryVM;
            try
            {
                var brewery = await _breweryService.GetBrewery(id);
                breweryVM = brewery.ToBreweryVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(breweryVM);
        }
        // GET: BreweriesController.cs/Details/5

        // GET: BreweriesController.cs/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BreweriesController.cs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBreweryViewModel model)
        {
            if (model == null)
                return BadRequest();

            var exists = await _breweryService.BreweryExists(model.Name, model.Country);
            if (exists)
                return StatusCode(409, $"Brewery '{model.Name}' already exists.");

            BreweryDTO breweryDTO = model.ToBreweryDTO();

            await _breweryService.Create(breweryDTO);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        // GET: BreweriesController.cs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            EditBreweryViewModel editBreweryVM;
            try
            {
                var brewery = await _breweryService.GetBrewery(id);
                editBreweryVM = brewery.ToEditBreweryVM();
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(editBreweryVM);
        }

        // POST: BreweriesController.cs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditBreweryViewModel model)
        {
            try
            {
                var brewery = model.ToBreweryDTO();
                await _breweryService.Update(id, brewery);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: BreweriesController.cs/Delete/5
        //[Route("Breweries/Delete/{id}")]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    BreweryViewModel breweryVM;
        //    try
        //    {
        //        var brewery = await _breweryService.GetBrewery(id);
        //        breweryVM = brewery.ToBreweryVM();
        //    }
        //    catch (Exception)
        //    {
        //        return NotFound();
        //        throw;
        //    }

        //    return View(breweryVM);
        //}

        // POST: BreweriesController.cs/Delete/5
        [HttpPost, ActionName("Delete")]
        [Route("Breweries/Delete/{id}")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _breweryService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

beer/Beers.Web/Views/Breweries/Create.cshtml
@model CreateBreweryViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container">
    <div class="py-100">
        <div class="d-flex pt-5 justify-content-between">
            <h1 class="">Create Brewery</h1>
            <a asp-action="Index">Back to List</a>
        </div>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

beer/Beers.Web/Views/Breweries/Delete.cshtml
@model BreweryViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brewery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

beer/Beers.Web/Views/Breweries/Details.cshtml
@model BreweryViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}




<section id="details" class="bg-gray vh-75 d-flex align-items-center">
    @*Controls*@
    <div id="controls" class="d-flex align-items-center">
        @if (User.IsInRole("Admin"))
        {
            <form asp-action="Delete" asp-route-id="@Model.Id">
                <button type="submit" class="btn btn-danger mr-2">Delete <i class="fas fa-trash-alt"></i></button>
            </form>
            @*<a class="btn btn-danger mr-2" asp-action="Delete" asp-route-id="@Model.Id">Delete <i class="fas fa-trash-alt"></i></a>*@
            <a class="btn btn-primary mr-2" asp-action="Edit" asp-route-id="@Model.Id">Edit <i class="far fa-edit"></i></a>
        }
        <a asp-action="Index">Back to List</a>
    </div>
    @*Controls / END*@
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                    <div class="frame">
                        <img src="~/images/beer-1513436_1920.jpg" alt="" width="100%" />
                    </div>
                </div>

                <div class="col-xs-12 col-sm-7 col-sm-push-1 col-md-7 col-lg-7">
                    <h2>
                        @Model.Name
                        <a target="_blank" class="text-primary" title="search on maps" href="http://maps.google.com/?q=@Model.Name"><i class="fas fa-map-marked-alt"></i></a>
                    </h2>
                    <h3 class="text-primary gr-h-family mb-2" title="Beers count">Beers: @Model.Beers.Count</h3>
                    <p class="mb-5 text-muted">
                        @if (Model.Country != null)
                        {
                            <a target="_blank" class="text-muted" title="show on map" href="http://maps.google.com/?q=@Model.Country.Name">@Model.Country.Name <i class="fas fa-map-marked-alt text-primary"></i></a>
                        }
                    </p>
                </div>

            </div>

        </div>
    </div>
</section>

@*Nav TABS*@
<nav>
    <div class="nav nav-tabs bg-gray" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-beers-tab" data-toggle="tab" href="#style-beers" role="tab" aria-controls="nav-home" aria-selected="true">Beers ( @Model.Beers.Count )</a>
    </div>
</nav>
@*NAV TABS / END*@

<div class="tab-content py-100" id="nav-tabContent">
    <div class="container">
        <div class="tab-pane fade show active" id="style-beers" role="tabpanel" aria-labelledby="nav-beers-tab">
            @if (Model.Beers.Count == 0)
            {
                <h3 class="text-primary gr-h-family text-center">This Brewery has no beers</h3>
            }

            @if (Model.Beers.Count > 0)
            {
                @if (Model.Beers.Count >= 4)
                {
                    <h3 class="text-primary gr-h-family text-center">Top 4 beers made by this Brewery</h3>
                }
                else
                {
                    <h3 class="text-primary gr-h-family text-center">Top @Model.Beers.Count beer/s made by this Brewery</h3>
                }
                <hr class="mb-5" />
                <div class="container">
                    <div class="row">
                        @if (Model.Beers.Count <= 4)
                        {
                            @foreach (var beer in Model.Beers)
                            {
                                <div class="col-md-3 col-sm-4">
                                    @Html.Partial("_BeerPartial", beer)
                                </div>
                            }
                        }
                        else
                        {
                            @for (var i = 0; i < 4; i++)
                            {
                                <div class="col-md-3 col-sm-4">
                                    @Html.Partial("_BeerPartial", Model.Beers.ToList()[i])
                                </div>
                            }
                        }
                    </div>
                </div>

            }
        </div>
    </div>
</div>

beer/Beers.Web/Views/Breweries/Edit.cshtml
@model EditBreweryViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Brewery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

beer/Beers.Web/Views/Breweries/Index.cshtml
@model IEnumerable<BreweryViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="bg-gray h-100 w-100">
    <div class="container" style="min-height: 100vh">
        <div class="py-100">
            <div class="d-flex justify-content-between mb-3" style="padding-top: 100px">
                <a asp-action="Create" class="btn btn-primary">Create New <i class="fas fa-plus"></i></a>
                <div class="d-flex">


                    <div class="search-form d-inline-flex mr-3">
                        <label for="search-input" class="m-0 mr-3 d-flex justify-content-center align-items-center font-weight-bold">Search:</label>
                        <div class="input-group">
                            <input id="search-input" type="text" class="form-control">
                            <div class="input-group-append">
                                <button onclick="Search()" class="btn btn-primary">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>


                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Order By
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("Index", "Breweries")?order=name_asc">Name Ascending</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "Breweries")?order=name_desc">Name Descending</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-sm-4 col-md-3 mb-5">
                        @Html.Partial("_BreweryPartial", item)
                    </div>
                }
            </div>
            <div class="d-flex mb-3 pt-5">
                <button class="btn btn-secondary mr-3" onclick="MovePrevious()">Prev</button>
                <button class="btn btn-primary" onclick="MoveNext()">Next</button>
            </div>
        </div>
    </div>
</div>